export const GET_TEAMS = 'GET_TEAMS';
export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const GET_SINGLE_MATCHES = 'GET_MATCHES';
export const GET_SINGLE_PLAYER = 'GET_SINGLE_MATCH';